[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.10", features = ["derive"] }
env_logger = "0.10.0"
lexer = { path = "../lexer" }
repl = { path = "../repl" }
flags = { path = "../flags" }
log = "0.4.17"
