[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
thiserror = "1.0"
lexer = { path = "../lexer" }
error = { path = "../error" }
flags = { path = "../flags" }
ast = { path = "../ast" }
env_logger = "0.10.0"
log = "0.4.17"
